services:
  db:
    image: postgres:15
    container_name: keyboard-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build:
      context: ./apps/server
    container_name: keyboard-server
    env_file:
      - ./apps/server/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    command: yarn start:dev
    volumes:
      - ./apps/server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build:
      context: ./apps/client
    container_name: keyboard-client
    env_file:
      - ./apps/client/.env
    ports:
      - "3000:3000"
    depends_on:
      - server
    command: npx next dev -H 0.0.0.0
    volumes:
      - ./apps/client:/usr/src/app
      # - /usr/src/app/node_modules

volumes:
  pgdata:
